name: ITHome Auto Sign

on:
  push:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  ithome_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 允许提交代码的权限

      # 清理旧文件（删除所有历史日志，重置 cleanup.log）
      - name: Cleanup old files
        run: |
          rm -rf log_*.txt  # 删除所有时间戳文件
          echo "Last cleanup at: $(date)" > cleanup.log  # 覆盖写入清理时间

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: python -m pip install --upgrade requests pydes

      # 生成新时间戳空文件（仅保留文件名）
      - name: Generate timestamp file
        run: |
          touch "log_$(date +%Y%m%d%H%M%S).txt"  # 动态生成空文件

      # 提交最新文件到仓库根目录
      - name: Commit files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A  # 添加所有变更（包括删除和新文件）
          git commit -m "[skip ci] Update files"
          git push origin master
