name: ITHome Auto Sign

on:
  push:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  ithome_sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 确保具有写入仓库的权限
          persist-credentials: true

      # 删除项目根目录下的旧日志
      - name: Cleanup old logs
        run: |
          rm -f ./log_*.txt
          echo "Cleanup completed at $(date)" >> ./cleanup.log

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: python -m pip install --upgrade requests pydes

      # 生成日志到项目根目录
      - name: Start Sign
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          USERHASH: ${{ secrets.USERHASH }}
        run: |
          LOG_FILE="./log_$(date +%Y%m%d%H%M%S).txt"
          python run.py > "${LOG_FILE}" 2>&1
          echo "Log saved to ${LOG_FILE}"

      # 提交日志到仓库根目录
      - name: Commit logs to root
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -f ./log_*.txt ./cleanup.log
          git commit -m "[skip ci] Add auto-generated logs $(date)"
          git push origin master
